# For physics topics, use the specific subtopics, e.g. "Astrophysics"
topic: "Computer Science"
# An empty list here will include all categories in a topic
# Use the natural language names of the topics, found here: https://arxiv.org
# Including more categories will result in more calls to the large language model
categories: ["Artificial Intelligence", "Computation and Language"]

# Relevance score threshold. abstracts that receive a score less than this from the large language model
# will have their papers filtered out.
#
# Must be within 1-10
threshold: 7

# A natural language statement that the large language model will use to judge which papers are relevant 
#
# For example:
#     "I am interested in complexity theory papers that establish upper bounds"
#     "gas chromatography, mass spectrometry"
#     "making lots of money"
#
# This can be empty, which just return a full list of papers with no judgement or filtering,
# in whatever order arXiv responds with.
interest: |
  1. 大模型体系，包括：预训练体系，后训练体系，数据体系，多模态，架构体系，推理体系，评估体系，上下文体系，具身智能
  2. 算力体系，包括：AI Infra, MLSys
  3. 开发体系，包括：Agent, RAG, Prompting优化, 开发者生态
  4. 应用体系，包括大模型产品，多模态产品，空间智能，AI4Science
